packages:
  - 'packages/*'
  - 'apps/*'
catalog:
  "@types/node": ^20.17.10
  "@types/react": ^19.0.1
  "@types/react-dom": ^19.0.2
  "@ai-sdk/openai": ^1.0.10
  "@cloudflare/workers-types": ^4.20241224.0
  "@types/bun": ^1.2.2
  "@date-fns/tz": ^1.2.0
  "@eslint/compat": ^1.2.4
  "@eslint/config-inspector": ^0.5.6
  "@eslint/eslintrc": ^3.2.0
  "@eslint/js": ^9.17.0
  "@evilmartians/lefthook": ^1.10.1
  "@fortawesome/fontawesome-svg-core": ^6.7.2
  "@fortawesome/free-brands-svg-icons": ^6.7.2
  "@fortawesome/free-solid-svg-icons": ^6.7.2
  "@fortawesome/react-fontawesome": ^0.2.2
  "@headlessui/react": ^2.2.0
  "@hono/standard-validator": ^0.1.1
  "@hono/vite-build": ^1.2.0
  "@hono/vite-dev-server": ^0.17.0
  "@hono/vite-ssg": ^0.1.0
  "@huggingface/inference": ^2.8.1
  "@langchain/core": ^0.2.17
  "@langchain/openai": ^0.2.4
  "@mantine/charts": ^7.15.2
  "@mantine/core": ^7.15.2
  "@mantine/dates": ^7.15.2
  "@mantine/form": ^7.15.2
  "@mantine/hooks": ^7.15.2
  "@mantine/modals": ^7.15.2
  "@mdx-js/loader": ^3.1.0
  "@mdx-js/react": ^3.1.0
  "@next/bundle-analyzer": ^15.1.1
  "@next/eslint-plugin-next": ^15.1.3
  "@next/mdx": ^15.1.1
  "@next/third-parties": ^15.1.1
  "@prisma/client": ^5.22.0
  "@react-hookz/web": ^24.0.4
  "@shikijs/transformers": ^1.24.2
  "@standard-schema/spec": ^1.0.0
  "@storybook/addon-actions": ^8.4.7
  "@storybook/addon-essentials": ^7.6.20
  "@storybook/addon-interactions": ^7.6.20
  "@storybook/addon-links": ^7.6.20
  "@storybook/addon-onboarding": ^1.0.11
  "@storybook/blocks": ^7.6.20
  "@storybook/manager-api": ^7.6.20
  "@storybook/nextjs": ^7.6.20
  "@storybook/react": ^7.6.20
  "@storybook/testing-library": ^0.2.2
  "@storybook/theming": ^7.6.20
  "@tailwindcss/container-queries": ^0.1.1
  "@tailwindcss/postcss": 4.0.0-beta.8
  "@testing-library/jest-dom": ^6.6.3
  "@testing-library/react": ^14.3.1
  "@twemoji/api": ^15.1.0
  "@types/eslint__js": ^8.42.3
  "@types/js-yaml": ^4.0.9
  "@types/jsdom": ^21.1.7
  "@types/katex": ^0.16.7
  "@types/mdx": ^2.0.13
  "@types/react-modal": ^3.16.3
  "@types/seedrandom": ^3.0.8
  "@types/webpack": ^5.28.5
  "@valibot/to-json-schema": 1.0.0-beta.5
  "@vanilla-extract/css": ^1.16.1
  "@vanilla-extract/next-plugin": ^2.4.7
  "@vercel/edge-config": ^1.4.0
  "@vercel/functions": ^1.5.2
  "@vercel/kv": ^1.0.1
  "@vitejs/plugin-react": ^4.3.4
  "@vitest/coverage-v8": 2.1.5
  "@vitest/ui": ^2.1.8
  ai: ^4.0.20
  autoprefixer: ^10.4.20
  better-react-mathjax: ^2.0.3
  better-typescript-lib: ^2.10.0
  budoux: ^0.6.3
  bufferutil: ^4.0.8
  chokidar: ^3.6.0
  classnames: ^2.5.1
  clipboardy: ^4.0.0
  cloudinary: ^2.5.1
  consola: ^3.2.3
  cssnano: ^6.1.2
  date-fns: ^4.1.0
  dayjs: ^1.11.13
  devicon: ^2.16.0
  drizzle-kit: ^0.28.1
  drizzle-orm: ^0.36.4
  eslint-config-prettier: ^9.1.0
  eslint-plugin-import: ^2.31.0
  eslint-plugin-n: ^17.15.1
  eslint-plugin-react: ^7.37.3
  eslint-plugin-react-compiler: 19.0.0-beta-201e55d-20241215
  eslint-plugin-react-hooks: ^5.1.0
  eslint-plugin-storybook: ^0.11.1
  eslint-plugin-testing-library: ^6.5.0
  eslint-plugin-unused-imports: ^4.1.4
  focus-trap: ^7.6.2
  framer-motion: ^11.15.0
  globals: ^15.14.0
  gray-matter: ^4.0.3
  happy-dom: ^15.11.7
  http-status-codes: ^2.3.0
  immer: ^10.1.1
  jotai: ^2.10.4
  js-yaml: ^4.1.0
  jsdom: ^25.0.1
  katex: ^0.16.19
  lru-cache: ^10.4.3
  mermaid: ^11.4.1
  microcms-js-sdk: ^3.1.2
  nanoid: ^5.0.9
  next-mdx-remote: ^5.0.0
  node-html-parser: ^7.0.1
  nookies: ^2.5.2
  postcss-preset-mantine: ^1.17.0
  postcss-simple-vars: ^7.0.1
  prettier: 3.3.3
  prettier-plugin-classnames: ^0.7.5
  prettier-plugin-merge: ^0.7.2
  prettier-plugin-tailwindcss: ^0.6.9
  prisma: ^5.22.0
  react-hook-form: ^7.54.1
  react-hot-toast: ^2.4.1
  react-loading-skeleton: ^3.5.0
  react-modal: ^3.16.3
  react-player: ^2.16.0
  react-rewards: ^2.0.4
  react-string-replace: ^1.1.1
  react-tooltip: ^5.28.0
  react-tweet: ^3.2.1
  react-twitter-widgets: ^1.11.0
  react-wrap-balancer: ^1.1.1
  react-youtube: ^10.1.0
  recharts: "2"
  rehype-katex: ^7.0.1
  rehype-raw: ^7.0.0
  rehype-slug: ^6.0.0
  rehype-unwrap-images: ^1.0.0
  remark-gfm: ^4.0.0
  remark-math: ^6.0.0
  remark-toc: ^9.0.0
  remeda: ^2.20.1
  seedrandom: ^3.0.5
  server-only: ^0.0.1
  shiki: ^1.24.2
  socket.io: ^4.8.1
  socket.io-client: ^4.8.1
  stable-hash: ^0.0.4
  storybook: ^7.6.20
  storybook-dark-mode: ^3.0.3
  tailwind-merge: ^2.5.5
  tailwind-variants: ^0.2.1
  ts-dedent: ^2.2.0
  ts-pattern: ^5.6.0
  tsr: ^1.3.3
  turbo: ^2.3.3
  typescript: ^5.7.2
  typescript-eslint: 8.14.0
  use-immer: ^0.9.0
  use-sound: ^4.0.3
  uuidv7: ^1.0.2
  valibot: 1.0.0-beta.15
  vite: ^6.0.6
  vitest: ^2.1.8
  webpack: ^5.97.1
  wrangler: ^3.99.0
  tailwindcss: ^3.4.17
  eslint: ^9.14.0
  eslint-config-next: ^15.1.3
  postcss: ^8.4.49
  next: ^15.1.2
  react: ^19.0.0
  react-dom: ^19.0.0
  swr: ^2.3.0
  hono: ^4.6.15
