packages:
  - packages/*
  - apps/*

catalog:
  '@ai-sdk/openai': 2.0.16
  '@cloudflare/workers-types': ^4.20250820.0
  '@date-fns/tz': ^1.4.1
  '@eslint/compat': ^1.3.2
  '@eslint/config-inspector': ^1.2.0
  '@eslint/eslintrc': ^3.3.1
  '@eslint/js': ^9.33.0
  '@evilmartians/lefthook': ^1.12.3
  '@fortawesome/fontawesome-svg-core': ^7.0.0
  '@fortawesome/free-brands-svg-icons': ^7.0.0
  '@fortawesome/free-solid-svg-icons': ^7.0.0
  '@fortawesome/react-fontawesome': ^0.2.5
  '@google/genai': ^1.16.0
  '@headlessui/react': ^2.2.7
  '@hono/standard-validator': ^0.1.4
  '@hono/vite-build': ^1.7.0
  '@hono/vite-dev-server': ^0.20.1
  '@hono/vite-ssg': ^0.2.0
  '@mantine/charts': ^8.2.5
  '@mantine/core': ^8.2.5
  '@mantine/dates': ^8.2.5
  '@mantine/form': ^8.2.5
  '@mantine/hooks': ^8.2.5
  '@mantine/modals': ^8.2.5
  '@mdx-js/loader': ^3.1.0
  '@mdx-js/react': ^3.1.0
  '@next/bundle-analyzer': ^15.5.0
  '@next/eslint-plugin-next': ^15.5.0
  '@next/mdx': ^15.5.0
  '@next/third-parties': ^15.5.0
  '@prisma/client': ^6.14.0
  '@react-hookz/web': ^25.1.1
  '@shikijs/transformers': ^3.11.0
  '@standard-schema/spec': ^1.0.0
  '@storybook/addon-actions': ^8.4.7
  '@storybook/addon-essentials': ^7.6.20
  '@storybook/addon-interactions': ^7.6.20
  '@storybook/addon-links': ^7.6.20
  '@storybook/addon-onboarding': ^1.0.11
  '@storybook/blocks': ^7.6.20
  '@storybook/manager-api': ^7.6.20
  '@storybook/nextjs': ^7.6.20
  '@storybook/react': ^7.6.20
  '@storybook/testing-library': ^0.2.2
  '@storybook/theming': ^7.6.20
  '@tailwindcss/container-queries': ^0.1.1
  '@tailwindcss/postcss': 4.1.11
  '@testing-library/dom': ^10.4.1
  '@testing-library/jest-dom': ^6.7.0
  '@testing-library/react': ^16.3.0
  '@twemoji/api': ^16.0.1
  '@types/bun': ^1.2.20
  '@types/eslint__js': ^9.14.0
  '@types/js-yaml': ^4.0.9
  '@types/katex': ^0.16.7
  '@types/mdx': ^2.0.13
  '@types/node': ^22.17.2
  '@types/react': ^19.1.10
  '@types/react-dom': ^19.1.7
  '@types/react-modal': ^3.16.3
  '@types/seedrandom': ^3.0.8
  '@types/webpack': ^5.28.5
  '@valibot/to-json-schema': 1.3.0
  '@vanilla-extract/css': ^1.17.4
  '@vanilla-extract/next-plugin': ^2.4.14
  '@vercel/edge-config': ^1.4.0
  '@vercel/functions': ^2.2.12
  '@vitejs/plugin-react': ^5.0.1
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  ai: 5.0.18
  autoprefixer: ^10.4.21
  babel-plugin-react-compiler: 19.1.0-rc.2
  better-react-mathjax: ^2.3.0
  better-typescript-lib: ^2.11.0
  budoux: ^0.7.0
  bufferutil: ^4.0.9
  chokidar: ^4.0.3
  classnames: ^2.5.1
  clipboardy: ^4.0.0
  cloudinary: ^2.7.0
  consola: ^3.4.2
  cssnano: ^7.1.0
  date-fns: ^4.1.0
  dayjs: ^1.11.13
  devicon: ^2.17.0
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.4
  eslint: ^9.33.0
  eslint-config-next: ^15.5.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-import: ^2.32.0
  eslint-plugin-n: ^17.21.3
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-compiler: 19.1.0-rc.2
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-storybook: ^9.1.2
  eslint-plugin-testing-library: ^7.6.6
  eslint-plugin-unused-imports: ^4.2.0
  focus-trap: ^7.6.5
  globals: ^16.3.0
  gray-matter: ^4.0.3
  happy-dom: ^18.0.1
  hono: ^4.9.2
  http-status-codes: ^2.3.0
  immer: ^10.1.1
  jotai: ^2.13.1
  js-yaml: ^4.1.0
  katex: ^0.16.22
  lru-cache: ^11.1.0
  mermaid: ^11.10.0
  microcms-js-sdk: ^3.2.0
  motion: ^12.23.12
  nanoid: ^5.1.5
  next: ^15.5.0
  next-mdx-remote: ^5.0.0
  node-html-parser: ^7.0.1
  nookies: ^2.5.2
  p-retry: ^7.0.0
  postcss: ^8.5.6
  postcss-preset-mantine: ^1.18.0
  postcss-simple-vars: ^7.0.1
  prettier: 3.6.2
  prettier-plugin-classnames: ^0.8.2
  prettier-plugin-merge: ^0.8.0
  prettier-plugin-tailwindcss: ^0.6.14
  prisma: ^6.14.0
  react: ^19.1.1
  react-dom: ^19.1.1
  react-hook-form: ^7.62.0
  react-hot-toast: ^2.6.0
  react-loading-skeleton: ^3.5.0
  react-modal: ^3.16.3
  react-player: ^3.3.1
  react-rewards: ^2.1.0
  react-string-replace: ^1.1.1
  react-tooltip: ^5.29.1
  react-tweet: ^3.2.2
  react-twitter-widgets: ^1.11.0
  react-wrap-balancer: ^1.1.1
  react-youtube: ^10.1.0
  rehype-katex: ^7.0.1
  rehype-raw: ^7.0.0
  rehype-slug: ^6.0.0
  rehype-unwrap-images: ^1.0.0
  remark-gfm: ^4.0.1
  remark-math: ^6.0.0
  remark-toc: ^9.0.0
  remeda: ^2.30.0
  seedrandom: ^3.0.5
  server-only: ^0.0.1
  shiki: ^3.11.0
  socket.io: ^4.8.1
  socket.io-client: ^4.8.1
  stable-hash: ^0.0.6
  storybook: ^7.6.20
  storybook-dark-mode: ^3.0.3
  swr: ^2.3.6
  tailwind-merge: ^2.5.5
  tailwind-variants: ^0.2.1
  tailwindcss: ^3.4.17
  ts-dedent: ^2.2.0
  ts-pattern: ^5.8.0
  tsr: ^1.3.4
  turbo: ^2.5.6
  type-fest: 4.41.0
  typescript: ^5.9.2
  typescript-eslint: 8.39.0
  use-immer: ^0.11.0
  use-sound: ^5.0.0
  uuidv7: ^1.0.2
  valibot: ^1.1.0
  vite: ^7.1.3
  vitest: ^3.2.4
  webpack: ^5.101.3
  wrangler: 3.105.0

catalogMode: prefer
