// Generated by Wrangler by running `wrangler types --env-interface Bindings`

export interface Bindings {
  KV: KVNamespace
  OPENAI_API_KEY: string
  TRPFROG_FUNCTIONS_SECRET: string
  NODE_ENV: string
  GEMINI_API_KEY: string
  BUCKET: R2Bucket
  DATABASE: D1Database
  ASSETS: Fetcher
}
