// Generated by Wrangler by running `wrangler types --env-interface Bindings`

export interface Bindings {
  DIFFUSION_KV: KVNamespace
  OPENAI_API_KEY: string
  TRPFROG_FUNCTIONS_SECRET: string
  HUGGINGFACE_TOKEN: string
  NODE_ENV: string
}
