import { ArrayValues } from 'type-fest'

export const balloonColors = ['blue', 'green', 'orange'] as const
export type BalloonColor = ArrayValues<typeof balloonColors>

export const confettiColors: Record<BalloonColor, string[]> = {
  // Generated by GPT-3.5
  blue: [
    '#00FFFF', // Cyan
    '#40E0D0', // Turquoise
    '#00CED1', // Dark Turquoise
    '#20B2AA', // Light Sea Green
    '#00BFFF', // Deep Sky Blue
  ],
  green: [
    '#B4D455', // Light Yellow Green
    '#9ACD32', // Medium Yellow Green
    '#7FFF00', // Chartreuse
    '#7CFC00', // Lawn Green
    '#ADFF2F', // Green Yellow
  ],
  orange: [
    '#FFA500', // Orange
    '#FF8C00', // Dark Orange
    '#FF7F50', // Coral
    '#FF6347', // Tomato
    '#FF4500', // Orange Red
  ],
}

export const balloonSoundUrl =
  'https://res.cloudinary.com/trpfrog/video/upload/v1652447772/balloon/break-immeditary.mp3'

export const normalBalloonImagePaths = balloonColors.map(
  color => `/images/balloon/${color}/normal.png` as const,
)
export const trembleBalloonImagePaths = balloonColors.map(
  color => `/images/balloon/${color}/tremble.gif` as const,
)
export const brokenBalloonImagePath = '/images/balloon/broken.png' as const
