'use client'

import { Dispatch, useId, useState } from 'react'

import { useReward } from 'react-rewards'

import styles from './index.module.scss'

import useSound from '@/../node_modules/use-sound'

export const balloonColors = ['blue', 'green', 'orange'] as const

type BalloonProps = {
  className?: string
  width: string
  height: string
  isBurst: boolean
  color: (typeof balloonColors)[number]
  onBurst?: () => void
}

let playSound = () => {}
export const useBalloonSound = (): [boolean, Dispatch<boolean>] => {
  const [isSoundEnabled, setSoundEnabled] = useState(false)
  const soundURL =
    'https://res.cloudinary.com/trpfrog/video/upload/v1652447772/balloon/break-immeditary.mp3'
  const [playFunction] = useSound(soundURL, { interrupt: false })
  playSound = isSoundEnabled ? playFunction : () => {}
  return [isSoundEnabled, setSoundEnabled]
}

const colors: Record<(typeof balloonColors)[number], string[]> = {
  // Generated by GPT-3.5
  blue: [
    '#00FFFF', // Cyan
    '#40E0D0', // Turquoise
    '#00CED1', // Dark Turquoise
    '#20B2AA', // Light Sea Green
    '#00BFFF', // Deep Sky Blue
  ],
  green: [
    '#B4D455', // Light Yellow Green
    '#9ACD32', // Medium Yellow Green
    '#7FFF00', // Chartreuse
    '#7CFC00', // Lawn Green
    '#ADFF2F', // Green Yellow
  ],
  orange: [
    '#FFA500', // Orange
    '#FF8C00', // Dark Orange
    '#FF7F50', // Coral
    '#FF6347', // Tomato
    '#FF4500', // Orange Red
  ],
}

export const Balloon = (props: BalloonProps) => {
  const balloonId = useId()
  const { reward } = useReward(balloonId, 'confetti', {
    zIndex: 100,
    startVelocity: 8,
    elementCount: 35,
    decay: 0.95,
    elementSize: 6,
    spread: 50,
    position: 'absolute',
    colors: colors[props.color],
  })

  return (
    <span
      style={{
        width: props.width,
        height: props.height,
        backgroundSize: `${props.width} ${props.height}`,
      }}
      className={`${styles.balloon} ${props.className}`}
      data-broken-balloon={props.isBurst}
      data-balloon-color={props.color}
      onClick={() => {
        if (!props.isBurst) {
          playSound()
          reward()
          props.onBurst?.()
        }
      }}
    >
      <span className={styles.starting_point_of_effect} id={balloonId} />
    </span>
  )
}
